language: java

cache:
  directories:
    - $HOME/.m2
    - $HOME/.zinc

install:
  - java -XX:+PrintFlagsFinal -version
  - mvn --version
  - mvn dependency:resolve-plugins --update-snapshots --settings .travis.settings.xml -e
  - mvn dependency:resolve --update-snapshots --settings .travis.settings.xml -e

script: mvn clean verify --update-snapshots --settings .travis.settings.xml -e

jdk: oraclejdk7
