language: java

cache:
  directories:
    - $HOME/.m2
    - $HOME/.zinc

install:
  - java -XX:+PrintFlagsFinal -version
  - mvn --version

script: mvn verify --update-snapshots --settings .travis.settings.xml -e

jdk: oraclejdk7
